# Generated by Django 5.1.3 on 2024-12-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_design_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_desc',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_desc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_name',
            field=models.CharField(max_length=150),
        ),
    ]
