# Generated by Django 5.1.3 on 2024-12-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_design_design_desc_alter_design_design_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='bid_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='current_highest_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requirement',
            name='minimum_bid_increment',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField()),
                ('bid_time', models.DateTimeField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'paid'), ('not paid', 'not paid')], default='pending', max_length=10)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.requirement')),
            ],
        ),
    ]
