# Generated by Django 5.1.3 on 2024-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_requirement_bid_end_date_requirement_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='initial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
