# Generated by Django 5.1.3 on 2024-12-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='designer',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'Designer'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
