# Generated by Django 5.1.3 on 2025-01-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_booking_address_booking_offline_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='bid_time',
        ),
        migrations.AddField(
            model_name='bidding',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='offline_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='offline_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bidding',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'Online Payment'), ('offline', 'Offline Payment')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
